package weheat

import "time"

// HeatPumpLogView mirrors HeatPumpLogViewDto.
type HeatPumpLogView struct {
	TimeBucket                                      *time.Time `json:"timeBucket,omitempty"`
	Interval                                        *string    `json:"interval,omitempty"`
	TimeCoveredInInterval                           *int       `json:"timeCoveredInInterval,omitempty"`
	HeatPumpStateStandby                            *int       `json:"heatPumpStateStandby,omitempty"`
	HeatPumpStateHeating                            *int       `json:"heatPumpStateHeating,omitempty"`
	HeatPumpStateCooling                            *int       `json:"heatPumpStateCooling,omitempty"`
	HeatPumpStateDHW                                *int       `json:"heatPumpStateDhw,omitempty"`
	HeatPumpStateLegionella                         *int       `json:"heatPumpStateLegionella,omitempty"`
	HeatPumpStateManualControl                      *int       `json:"heatPumpStateManualControl,omitempty"`
	HeatPumpStateDHWDefrost                         *int       `json:"heatPumpStateDhwDefrost,omitempty"`
	HeatPumpStateHeatingDefrost                     *int       `json:"heatPumpStateHeatingDefrost,omitempty"`
	ControlBridgeStatusWaterPump                    *int       `json:"controlBridgeStatusWaterPump,omitempty"`
	ControlBridgeStatusGasBoiler                    *int       `json:"controlBridgeStatusGasBoiler,omitempty"`
	ControlBridgeStatusElectricHeater               *int       `json:"controlBridgeStatusElectricHeater,omitempty"`
	ControlBridgeStatusWaterPump2                   *int       `json:"controlBridgeStatusWaterPump2,omitempty"`
	T1Average                                       *float64   `json:"t1Average,omitempty"`
	T1Min                                           *float64   `json:"t1Min,omitempty"`
	T1Max                                           *float64   `json:"t1Max,omitempty"`
	T2Average                                       *float64   `json:"t2Average,omitempty"`
	T2Min                                           *float64   `json:"t2Min,omitempty"`
	T2Max                                           *float64   `json:"t2Max,omitempty"`
	TAirInAverage                                   *float64   `json:"tAirInAverage,omitempty"`
	TAirInMin                                       *float64   `json:"tAirInMin,omitempty"`
	TAirInMax                                       *float64   `json:"tAirInMax,omitempty"`
	TAirOutAverage                                  *float64   `json:"tAirOutAverage,omitempty"`
	TAirOutMin                                      *float64   `json:"tAirOutMin,omitempty"`
	TAirOutMax                                      *float64   `json:"tAirOutMax,omitempty"`
	TWaterInAverage                                 *float64   `json:"tWaterInAverage,omitempty"`
	TWaterInMin                                     *float64   `json:"tWaterInMin,omitempty"`
	TWaterInMax                                     *float64   `json:"tWaterInMax,omitempty"`
	TWaterOutAverage                                *float64   `json:"tWaterOutAverage,omitempty"`
	TWaterOutMin                                    *float64   `json:"tWaterOutMin,omitempty"`
	TWaterOutMax                                    *float64   `json:"tWaterOutMax,omitempty"`
	TWaterHouseInAverage                            *float64   `json:"tWaterHouseInAverage,omitempty"`
	TWaterHouseInMin                                *float64   `json:"tWaterHouseInMin,omitempty"`
	TWaterHouseInMax                                *float64   `json:"tWaterHouseInMax,omitempty"`
	TRoomAverage                                    *float64   `json:"tRoomAverage,omitempty"`
	TRoomMin                                        *float64   `json:"tRoomMin,omitempty"`
	TRoomMax                                        *float64   `json:"tRoomMax,omitempty"`
	TRoomTargetAverage                              *float64   `json:"tRoomTargetAverage,omitempty"`
	TRoomTargetMin                                  *float64   `json:"tRoomTargetMin,omitempty"`
	TRoomTargetMax                                  *float64   `json:"tRoomTargetMax,omitempty"`
	TThermostatSetpointAverage                      *float64   `json:"tThermostatSetpointAverage,omitempty"`
	TThermostatSetpointMin                          *float64   `json:"tThermostatSetpointMin,omitempty"`
	TThermostatSetpointMax                          *float64   `json:"tThermostatSetpointMax,omitempty"`
	OTBoilerFeedTemperatureAverage                  *float64   `json:"otBoilerFeedTemperatureAverage,omitempty"`
	OTBoilerFeedTemperatureMin                      *float64   `json:"otBoilerFeedTemperatureMin,omitempty"`
	OTBoilerFeedTemperatureMax                      *float64   `json:"otBoilerFeedTemperatureMax,omitempty"`
	OTBoilerReturnTemperatureAverage                *float64   `json:"otBoilerReturnTemperatureAverage,omitempty"`
	OTBoilerReturnTemperatureMin                    *float64   `json:"otBoilerReturnTemperatureMin,omitempty"`
	OTBoilerReturnTemperatureMax                    *float64   `json:"otBoilerReturnTemperatureMax,omitempty"`
	ThermostatStateOff                              *int       `json:"thermostatStateOff,omitempty"`
	ThermostatStateOn                               *int       `json:"thermostatStateOn,omitempty"`
	RPMAverage                                      *float64   `json:"rpmAverage,omitempty"`
	RPMMin                                          *float64   `json:"rpmMin,omitempty"`
	RPMMax                                          *float64   `json:"rpmMax,omitempty"`
	CentralHeatingFlowAverage                       *float64   `json:"centralHeatingFlowAverage,omitempty"`
	CentralHeatingFlowMin                           *float64   `json:"centralHeatingFlowMin,omitempty"`
	CentralHeatingFlowMax                           *float64   `json:"centralHeatingFlowMax,omitempty"`
	CentralHeatingFlowStateStandby                  *int       `json:"centralHeatingFlowStateStandby,omitempty"`
	CentralHeatingFlowStateStandbyNoPWM             *int       `json:"centralHeatingFlowStateStandbyNoPwm,omitempty"`
	CentralHeatingFlowStateMotorBlocked             *int       `json:"centralHeatingFlowStateMotorBlocked,omitempty"`
	CentralHeatingFlowStatePumping                  *int       `json:"centralHeatingFlowStatePumping,omitempty"`
	CentralHeatingFlowStatePumpingNoPWM             *int       `json:"centralHeatingFlowStatePumpingNoPwm,omitempty"`
	CentralHeatingFlowStateSuboptimalRunning        *int       `json:"centralHeatingFlowStateSuboptimalRunning,omitempty"`
	CentralHeatingFlowStateStoppedMomentarily       *int       `json:"centralHeatingFlowStateStoppedMomentarily,omitempty"`
	CentralHeatingFlowStateStoppedPermanentDamage   *int       `json:"centralHeatingFlowStateStoppedPermanentDamage,omitempty"`
	DHWFlowAverage                                  *float64   `json:"dhwFlowAverage,omitempty"`
	DHWFlowMin                                      *float64   `json:"dhwFlowMin,omitempty"`
	DHWFlowMax                                      *float64   `json:"dhwFlowMax,omitempty"`
	DHWFlowStateStandby                             *int       `json:"dhwFlowStateStandby,omitempty"`
	DHWFlowStateStandbyNoPWM                        *int       `json:"dhwFlowStateStandbyNoPwm,omitempty"`
	DHWFlowStateMotorBlocked                        *int       `json:"dhwFlowStateMotorBlocked,omitempty"`
	DHWFlowStatePumping                             *int       `json:"dhwFlowStatePumping,omitempty"`
	DHWFlowStatePumpingNoPWM                        *int       `json:"dhwFlowStatePumpingNoPwm,omitempty"`
	DHWFlowStateSuboptimalRunning                   *int       `json:"dhwFlowStateSuboptimalRunning,omitempty"`
	DHWFlowStateStoppedMomentarily                  *int       `json:"dhwFlowStateStoppedMomentarily,omitempty"`
	DHWFlowStateStoppedPermanentDamage              *int       `json:"dhwFlowStateStoppedPermanentDamage,omitempty"`
	SignalStrengthAverage                           *float64   `json:"signalStrengthAverage,omitempty"`
	SignalStrengthMin                               *int       `json:"signalStrengthMin,omitempty"`
	SignalStrengthMax                               *int       `json:"signalStrengthMax,omitempty"`
	RPMLimiterAverage                               *float64   `json:"rpmLimiterAverage,omitempty"`
	RPMLimiterMin                                   *float64   `json:"rpmLimiterMin,omitempty"`
	RPMLimiterMax                                   *float64   `json:"rpmLimiterMax,omitempty"`
	RPMLimiterNoLimit                               *int       `json:"rpmLimiterNoLimit,omitempty"`
	RPMLimiterPowerLimit                            *int       `json:"rpmLimiterPowerLimit,omitempty"`
	RPMLimiterDefrost                               *int       `json:"rpmLimiterDefrost,omitempty"`
	RPMLimiterSilentHours                           *int       `json:"rpmLimiterSilentHours,omitempty"`
	RPMLimiterHPControl                             *int       `json:"rpmLimiterHPControl,omitempty"`
	RPMLimiterPressure                              *int       `json:"rpmLimiterPressure,omitempty"`
	RPMLimiterWaterOut                              *int       `json:"rpmLimiterWaterOut,omitempty"`
	RPMLimiterEnvelope                              *int       `json:"rpmLimiterEnvelope,omitempty"`
	RPMLimiterHouseIn                               *int       `json:"rpmLimiterHouseIn,omitempty"`
	PCompressorInAverage                            *float64   `json:"pCompressorInAverage,omitempty"`
	PCompressorInMin                                *float64   `json:"pCompressorInMin,omitempty"`
	PCompressorInMax                                *float64   `json:"pCompressorInMax,omitempty"`
	PCompressorOutAverage                           *float64   `json:"pCompressorOutAverage,omitempty"`
	PCompressorOutMin                               *float64   `json:"pCompressorOutMin,omitempty"`
	PCompressorOutMax                               *float64   `json:"pCompressorOutMax,omitempty"`
	PCompressorInTargetAverage                      *float64   `json:"pCompressorInTargetAverage,omitempty"`
	PCompressorInTargetMin                          *float64   `json:"pCompressorInTargetMin,omitempty"`
	PCompressorInTargetMax                          *float64   `json:"pCompressorInTargetMax,omitempty"`
	TCompressorInAverage                            *float64   `json:"tCompressorInAverage,omitempty"`
	TCompressorInMin                                *float64   `json:"tCompressorInMin,omitempty"`
	TCompressorInMax                                *float64   `json:"tCompressorInMax,omitempty"`
	TCompressorOutAverage                           *float64   `json:"tCompressorOutAverage,omitempty"`
	TCompressorOutMin                               *float64   `json:"tCompressorOutMin,omitempty"`
	TCompressorOutMax                               *float64   `json:"tCompressorOutMax,omitempty"`
	TCompressorInTransientAverage                   *float64   `json:"tCompressorInTransientAverage,omitempty"`
	TCompressorInTransientMin                       *float64   `json:"tCompressorInTransientMin,omitempty"`
	TCompressorInTransientMax                       *float64   `json:"tCompressorInTransientMax,omitempty"`
	TCompressorOutTransientAverage                  *float64   `json:"tCompressorOutTransientAverage,omitempty"`
	TCompressorOutTransientMin                      *float64   `json:"tCompressorOutTransientMin,omitempty"`
	TCompressorOutTransientMax                      *float64   `json:"tCompressorOutTransientMax,omitempty"`
	DeltaTCompressorInSuperheatAverage              *float64   `json:"deltaTCompressorInSuperheatAverage,omitempty"`
	DeltaTCompressorInSuperheatMin                  *float64   `json:"deltaTCompressorInSuperheatMin,omitempty"`
	DeltaTCompressorInSuperheatMax                  *float64   `json:"deltaTCompressorInSuperheatMax,omitempty"`
	FanAverage                                      *float64   `json:"fanAverage,omitempty"`
	FanMin                                          *float64   `json:"fanMin,omitempty"`
	FanMax                                          *float64   `json:"fanMax,omitempty"`
	FanPowerAverage                                 *float64   `json:"fanPowerAverage,omitempty"`
	FanPowerMin                                     *float64   `json:"fanPowerMin,omitempty"`
	FanPowerMax                                     *float64   `json:"fanPowerMax,omitempty"`
	TemperatureErrorIntegralAverage                 *float64   `json:"temperatureErrorIntegralAverage,omitempty"`
	TemperatureErrorIntegralMin                     *float64   `json:"temperatureErrorIntegralMin,omitempty"`
	TemperatureErrorIntegralMax                     *float64   `json:"temperatureErrorIntegralMax,omitempty"`
	DTCNone                                         *int       `json:"dtcNone,omitempty"`
	DTCContinue                                     *int       `json:"dtcContinue,omitempty"`
	DTCCompressorOff                                *int       `json:"dtcCompressorOff,omitempty"`
	DTCDefrostForbidden                             *int       `json:"dtcDefrostForbidden,omitempty"`
	DTCRequestService                               *int       `json:"dtcRequestService,omitempty"`
	DTCUseHeatingCurve                              *int       `json:"dtcUseHeatingCurve,omitempty"`
	DTCDHWForbidden                                 *int       `json:"dtcDhwForbidden,omitempty"`
	DTCError                                        *int       `json:"dtcError,omitempty"`
	DTCInactive                                     *int       `json:"dtcInactive,omitempty"`
	ControlBridgeStatusDHWValve                     *int       `json:"controlBridgeStatusDhwValve,omitempty"`
	ValveAverage                                    *int       `json:"valveAverage,omitempty"`
	ValveMin                                        *int       `json:"valveMin,omitempty"`
	ValveMax                                        *int       `json:"valveMax,omitempty"`
	TBoardAverage                                   *float64   `json:"tBoardAverage,omitempty"`
	TBoardMin                                       *float64   `json:"tBoardMin,omitempty"`
	TBoardMax                                       *float64   `json:"tBoardMax,omitempty"`
	TInverterAverage                                *float64   `json:"tInverterAverage,omitempty"`
	TInverterMin                                    *float64   `json:"tInverterMin,omitempty"`
	TInverterMax                                    *float64   `json:"tInverterMax,omitempty"`
	CompressorPowerLowAccuracyAverage               *float64   `json:"compressorPowerLowAccuracyAverage,omitempty"`
	CompressorPowerLowAccuracyMin                   *float64   `json:"compressorPowerLowAccuracyMin,omitempty"`
	CompressorPowerLowAccuracyMax                   *float64   `json:"compressorPowerLowAccuracyMax,omitempty"`
	CMMassPowerInStandbyAverage                     *float64   `json:"cmMassPowerInStandbyAverage,omitempty"`
	CMMassPowerInStandbyMin                         *float64   `json:"cmMassPowerInStandbyMin,omitempty"`
	CMMassPowerInStandbyMax                         *float64   `json:"cmMassPowerInStandbyMax,omitempty"`
	CMMassPowerInHeatingAverage                     *float64   `json:"cmMassPowerInHeatingAverage,omitempty"`
	CMMassPowerInHeatingMin                         *float64   `json:"cmMassPowerInHeatingMin,omitempty"`
	CMMassPowerInHeatingMax                         *float64   `json:"cmMassPowerInHeatingMax,omitempty"`
	CMMassPowerInCoolingAverage                     *float64   `json:"cmMassPowerInCoolingAverage,omitempty"`
	CMMassPowerInCoolingMin                         *float64   `json:"cmMassPowerInCoolingMin,omitempty"`
	CMMassPowerInCoolingMax                         *float64   `json:"cmMassPowerInCoolingMax,omitempty"`
	CMMassPowerInHeatingDefrostAverage              *float64   `json:"cmMassPowerInHeatingDefrostAverage,omitempty"`
	CMMassPowerInHeatingDefrostMin                  *float64   `json:"cmMassPowerInHeatingDefrostMin,omitempty"`
	CMMassPowerInHeatingDefrostMax                  *float64   `json:"cmMassPowerInHeatingDefrostMax,omitempty"`
	CMMassPowerInDHWDefrostAverage                  *float64   `json:"cmMassPowerInDhwDefrostAverage,omitempty"`
	CMMassPowerInDHWDefrostMin                      *float64   `json:"cmMassPowerInDhwDefrostMin,omitempty"`
	CMMassPowerInDHWDefrostMax                      *float64   `json:"cmMassPowerInDhwDefrostMax,omitempty"`
	CMMassPowerInDefrostAverage                     *float64   `json:"cmMassPowerInDefrostAverage,omitempty"`
	CMMassPowerInDefrostMin                         *float64   `json:"cmMassPowerInDefrostMin,omitempty"`
	CMMassPowerInDefrostMax                         *float64   `json:"cmMassPowerInDefrostMax,omitempty"`
	CMMassPowerInDHWAverage                         *float64   `json:"cmMassPowerInDhwAverage,omitempty"`
	CMMassPowerInDHWMin                             *float64   `json:"cmMassPowerInDhwMin,omitempty"`
	CMMassPowerInDHWMax                             *float64   `json:"cmMassPowerInDhwMax,omitempty"`
	CMMassPowerInManualControlAverage               *float64   `json:"cmMassPowerInManualControlAverage,omitempty"`
	CMMassPowerInManualControlMin                   *float64   `json:"cmMassPowerInManualControlMin,omitempty"`
	CMMassPowerOutHeatingDefrostAverage             *float64   `json:"cmMassPowerOutHeatingDefrostAverage,omitempty"`
	CMMassPowerOutHeatingDefrostMin                 *float64   `json:"cmMassPowerOutHeatingDefrostMin,omitempty"`
	CMMassPowerOutHeatingDefrostMax                 *float64   `json:"cmMassPowerOutHeatingDefrostMax,omitempty"`
	CMMassPowerOutDHWDefrostAverage                 *float64   `json:"cmMassPowerOutDhwDefrostAverage,omitempty"`
	CMMassPowerOutDHWDefrostMin                     *float64   `json:"cmMassPowerOutDhwDefrostMin,omitempty"`
	CMMassPowerOutDHWDefrostMax                     *float64   `json:"cmMassPowerOutDhwDefrostMax,omitempty"`
	CMMassPowerInManualControlMax                   *float64   `json:"cmMassPowerInManualControlMax,omitempty"`
	CMMassPowerOutStandbyAverage                    *float64   `json:"cmMassPowerOutStandbyAverage,omitempty"`
	CMMassPowerOutStandbyMin                        *float64   `json:"cmMassPowerOutStandbyMin,omitempty"`
	CMMassPowerOutStandbyMax                        *float64   `json:"cmMassPowerOutStandbyMax,omitempty"`
	CMMassPowerOutHeatingAverage                    *float64   `json:"cmMassPowerOutHeatingAverage,omitempty"`
	CMMassPowerOutHeatingMin                        *float64   `json:"cmMassPowerOutHeatingMin,omitempty"`
	CMMassPowerOutHeatingMax                        *float64   `json:"cmMassPowerOutHeatingMax,omitempty"`
	CMMassPowerOutCoolingAverage                    *float64   `json:"cmMassPowerOutCoolingAverage,omitempty"`
	CMMassPowerOutCoolingMin                        *float64   `json:"cmMassPowerOutCoolingMin,omitempty"`
	CMMassPowerOutCoolingMax                        *float64   `json:"cmMassPowerOutCoolingMax,omitempty"`
	CMMassPowerOutDefrostAverage                    *float64   `json:"cmMassPowerOutDefrostAverage,omitempty"`
	CMMassPowerOutDefrostMin                        *float64   `json:"cmMassPowerOutDefrostMin,omitempty"`
	CMMassPowerOutDefrostMax                        *float64   `json:"cmMassPowerOutDefrostMax,omitempty"`
	CMMassPowerOutDHWAverage                        *float64   `json:"cmMassPowerOutDhwAverage,omitempty"`
	CMMassPowerOutDHWMin                            *float64   `json:"cmMassPowerOutDhwMin,omitempty"`
	CMMassPowerOutDHWMax                            *float64   `json:"cmMassPowerOutDhwMax,omitempty"`
	CMMassPowerOutManualControlAverage              *float64   `json:"cmMassPowerOutManualControlAverage,omitempty"`
	CMMassPowerOutManualControlMin                  *float64   `json:"cmMassPowerOutManualControlMin,omitempty"`
	CMMassPowerOutManualControlMax                  *float64   `json:"cmMassPowerOutManualControlMax,omitempty"`
	InverterInputVoltageAverage                     *float64   `json:"inverterInputVoltageAverage,omitempty"`
	InverterInputVoltageMin                         *float64   `json:"inverterInputVoltageMin,omitempty"`
	InverterInputVoltageMax                         *float64   `json:"inverterInputVoltageMax,omitempty"`
	CentralHeatingPWMRequestedDutyCycleAverage      *float64   `json:"centralHeatingPwmRequestedDutyCycleAverage,omitempty"`
	CentralHeatingPWMRequestedDutyCycleMin          *float64   `json:"centralHeatingPwmRequestedDutyCycleMin,omitempty"`
	CentralHeatingPWMRequestedDutyCycleMax          *float64   `json:"centralHeatingPwmRequestedDutyCycleMax,omitempty"`
	CentralHeatingPWMRequestedDutyCycleStateStandby *int       `json:"centralHeatingPwmRequestedDutyCycleStateStandby,omitempty"`
	CentralHeatingPWMRequestedDutyCycleStatePumping *int       `json:"centralHeatingPwmRequestedDutyCycleStatePumping,omitempty"`
	DHWPWMRequestedDutyCycleAverage                 *float64   `json:"dhwPwmRequestedDutyCycleAverage,omitempty"`
	DHWPWMRequestedDutyCycleMin                     *float64   `json:"dhwPwmRequestedDutyCycleMin,omitempty"`
	DHWPWMRequestedDutyCycleMax                     *float64   `json:"dhwPwmRequestedDutyCycleMax,omitempty"`
	DHWPWMRequestedDutyCycleStateStandby            *int       `json:"dhwPwmRequestedDutyCycleStateStandby,omitempty"`
	DHWPWMRequestedDutyCycleStatePumping            *int       `json:"dhwPwmRequestedDutyCycleStatePumping,omitempty"`
	IndoorUnitHeaterTemperatureAverage              *float64   `json:"indoorUnitHeaterTemperatureAverage,omitempty"`
	IndoorUnitHeaterTemperatureMin                  *float64   `json:"indoorUnitHeaterTemperatureMin,omitempty"`
	IndoorUnitHeaterTemperatureMax                  *float64   `json:"indoorUnitHeaterTemperatureMax,omitempty"`
	IndoorUnitInputCurrentAverage                   *float64   `json:"indoorUnitInputCurrentAverage,omitempty"`
	IndoorUnitInputCurrentMin                       *float64   `json:"indoorUnitInputCurrentMin,omitempty"`
	IndoorUnitInputCurrentMax                       *float64   `json:"indoorUnitInputCurrentMax,omitempty"`
	SignalSINRAverage                               *float64   `json:"signalSinrAverage,omitempty"`
	SignalSINRMin                                   *float64   `json:"signalSinrMin,omitempty"`
	SignalSINRMax                                   *float64   `json:"signalSinrMax,omitempty"`
}
